      - name: Build EXE (onedir)
        shell: cmd
        run: pyinstaller --clean --windowed --name "DroneCalculator" --noupx ^
             --add-data "drone_app.py;." ^
             --collect-all streamlit --collect-all numpy --collect-all pandas --collect-all reportlab ^
             --hidden-import=importlib.metadata ^
             desktop_app.py

      - name: Zip dist folder
        shell: cmd
        run: powershell -NoProfile -Command "Compress-Archive -Path dist\\DroneCalculator\\* -DestinationPath DroneCalculator_onedir.zip"

      - name: Upload onedir artifact
        uses: actions/upload-artifact@v4
        with:
         

