name: Build Windows EXE

on:
  workflow_dispatch: {}   # manual run ke liye button milega Actions me
  push:
    branches: [ main ]    # jab bhi main branch pe push karoge, build chalega

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
          pip install pyinstaller pywebview

      - name: Build EXE
        run: |
          pyinstaller --clean --onefile --noconsole --name "DroneCalculator" ^
            --add-data "drone_app.py;." ^
            --collect-all streamlit ^
            --collect-all numpy ^
            --collect-all pandas ^
            --collect-all reportlab ^
            --hidden-import=importlib.metadata ^
            desktop_app.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: DroneCalculator-windows
          path: dist/DroneCalculator.exe
